"use strict";

import Authenticators from './interface.mjs';

/// Import 3rd part libraries
import jwt from "jsonwebtoken";

/// Import common libraries
import Fetch from "../../../common/fetch.mjs";

/// Module-scoped variables
let schema;
let logger;
let validate;
let fetch;

/// Firebase constant values
const GOOGLE_CERTS_URL = "https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com";
const GOOGLE_TOKEN_URL = "https://securetoken.google.com"

export default class Authenticator extends Authenticators {

    #cache;

    constructor(__schema, __logger, __validate) {
        super()

        /// Set module varaibles
        schema = __schema;
        logger = __logger;
        validate = __validate;

        /// Validate google client id if it exists inside environment variables
        if(validate.Property.isExistsKey(process.env, "AUTH_FIREBASE_PROVIDERS").result == false) throw new Error("AUTH_FIREBASE_PROVIDERS is not defined.");

        /// Validate google client id if it exists inside environment variables
        if(validate.Property.isExistsKey(process.env, "AUTH_FIREBASE_PROJECTID").result == false) throw new Error("AUTH_FIREBASE_PROJECTID is not defined.");

        this.#cache = new Cache();
        
        fetch = new Fetch(schema, logger);

        logger.debug("firebase plugin instantiated.")
    }

    async init(){

        try {

            logger.debug("Initializing plugin [firebase]")

            /// Cache public key from google firebase
            const firebase_cached = await this.#cache.getKeys("init");

            /// Ensure caching of public key is successful
            if(firebase_cached.success == false) throw firebase_cached.error;

            logger.debug("Firebase plugin successfully initialized")

            return new schema.Operation({ 
                success : true 
            });
        }
        catch(e) {

            logger.error(`Failed to initialize authenticator. ${ e.stack }`);

            return new schema.Operation({
                error : new Error(e.message)
            })
        }
    }

    /**
     * This is the function required to generate token by this application
     * During the signin process, users are expected to provide the jwt token
     * generated by firebase
     * 
     * Parameters: 
     *  - oauth_token
     */
    async signin(body){ 

        try {
            logger.info("Sign in request received. Validating request");

            /// Ensure body contains oauth_token parameter
            if(validate.Property.isExistsKey(body, "oauth_token").result == false) throw new Error("Missing oauth_token.")
            
            /// Ensure string is not empty
            if(validate.String.isNotEmpty(body.oauth_token).result == false) throw new Error("Invalid oauth_token.");

            // Decode token to get the header (for 'kid')
            const decoded = jwt.decode(body.oauth_token, { complete: true });

            /// Ensure value is in correct format
            if (!decoded || !decoded.header || !decoded.header.kid) throw new Error('Invalid token structure');

            /// Retrieve google's public key from cache
            const cache_firebase_keys = await this.#cache.getKeys(decoded.header.kid);

            /// Ensure retrieval from cache is successful
            if(cache_firebase_keys.success == false) throw cache_firebase_keys.error;

            /// Otherwise, store actual value
            const google_cert_pubkey = cache_firebase_keys.data.google_cert_pubkey;

            /// Second attempt, throw failure
            if(validate.Property.isExistsKey(google_cert_pubkey, decoded.header.kid).result == false) throw new jwt.TokenExpiredError("Invalid token.");

            /// Validate if email address exists
            if(validate.Property.isExistsKey(decoded.payload, "email").result == false) throw new Error("Email is not known from token payload.");

            /// Validate if email_verifed exists
            if(validate.Property.isExistsKey(decoded.payload, "email_verified").result == false) throw new Error("Email verified is not known from token payload.");

            /// Ensure email address was verified
            if(validate.Type.isBoolean(decoded.payload.email_verified).result == false) throw new Error("Email verified is not valid.");

            /// Ensure email_verified is set to true only when not in dev
            if(decoded.payload.email_verified == false) {
                
                /// Skip email verification check if running on dev environment
                if(process.env.NODE_ENV === "dev") logger.debug(`Detected dev environment. Skipping email verification check`);
                    
                /// Otherwise, throw error due to email is not verified
                else throw new Error("Email is not verified.");

            }

            logger.debug(`Verifying signin attempt for user [${ decoded.payload.email }]`)

            /// Verify the token
            const payload = jwt.verify(body.oauth_token, google_cert_pubkey[decoded.header.kid], {
                algorithms: ['RS256'],
                audience: process.env.AUTH_FIREBASE_PROJECTID,
                issuer: `${ GOOGLE_TOKEN_URL }/${ process.env.AUTH_FIREBASE_PROJECTID }`
            });

            logger.debug(`User [${ payload.email }] successfullly authenticated!`);

            return new schema.Authentication.SignIn({
                success : true,
                authenticated : true,
                username : payload.email,
                userid : payload.user_id
            })

        }
        catch(e) {

            logger.error(`Failed to sign in. ${ e.stack }`);

            switch (e.name) {
                /// Handle expired token. Send signal to client to retry
                case "TokenExpiredError" : return new schema.Authentication.SignIn({
                    success : true,
                    authenticated : false,
                    retry : true
                }); 

                /// Handle invalid token
                case "JsonWebTokenError" : return new schema.Authentication.SignIn({
                    success : true,
                    authenticated : false
                });

                /// Unhandled exceptions
                default : return new schema.Authentication.SignIn({
                    error : new Error(e.message)
                })
            }
        }
     }

    /// This is handled from AWS API Gateway token authorizer
    verify(){  }


    info(){  }
}


const Cache = class {
        
    /// Stores cache of google cert
    #google_cert_pubkey;

    async getKeys(kid){

        /// If the kid supplied does not exists from cache, refresh cache
        if(validate.Property.isExistsKey(this.#google_cert_pubkey, kid).result == false) {

            logger.debug(`kid [${ kid }] does not exists from local cache. Refreshing...`);

            return await this.#retrieveFirebaseKeys();
        }

        logger.debug(`kid [${ kid }] found on local cache.`);
        /// Else, return value
        return new schema.Operation({
            success : true,
            data : {
                google_cert_pubkey : this.#google_cert_pubkey
            }
        })
    }
    async #retrieveFirebaseKeys() {

        try {

            logger.debug(`Retrieving public key from google firebase.`);

            /// Retrieve google firebase public key
            const response = await fetch.get({ 
                url : GOOGLE_CERTS_URL
            });

            /// Ensure response is successful
            if(response.success == false) throw new Error(`Returns failure. ${ response.error.message }`)

            /// Ensure response returns 200 response code
            if(response.code != 200) throw new Error(`Returns non-200 response code. ${ response.code }. ${ response.error.message }`)
            
            logger.debug("Successfully retrieved public key from google secure token system")

            this.#google_cert_pubkey = { ...this.#google_cert_pubkey, ...(await response.data.json()) };

            return new schema.Operation({ 
                success : true,
                data : {
                    google_cert_pubkey : this.#google_cert_pubkey
                }
            });
        }
        catch(e) {

            logger.error(`Failed to cache public key. ${ e.stack }`);

            return new schema.Operation({ 
                error : new Error(e.message)
            });

        }
    }
}